### ISSUE TITLE
Application wont proceed further

### ISSUE THREAD

**Issue by nepal12** [adityadroid/Messio#29]
Hi, I have created my own package and followed all your steps. On application start after pressing Sign in with google I get a dialog box with account selection However when I select my gmail , application, there will be a quick flicker on
 the screen then application shows me the start page where it asks me to "Sign In with google". I get following error:

```
W/ActivityThread(29757): handleWindowVisibility: no activity for token android.os.BinderProxy@81c22e0
I/flutter (29757): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
I/flutter (29757): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
I/flutter (29757): <asynchronous suspension>
I/flutter (29757): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:344:48)
I/flutter (29757): <asynchronous suspension>
I/flutter (29757): #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:218:23)
I/flutter (29757): <asynchronous suspension>
I/flutter (29757): #4      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:257:20)
I/flutter (29757): #5      GoogleSignIn.signIn (package:google_sign_in/google_sign_in.dart:324:48)
I/flutter (29757): #6      AuthenticationProvider.signInWithGoogle (package:blabla/providers/AuthenticationProvider.dart:18:28)
I/flutter (29757): <asynchronous suspension>
I/flutter (29757): #7      AuthenticationRepository.signInWithGoogle (package:blabla/repositories/AuthenticationRepository.dart:11:30)
I/flutter (29757): #8      AuthenticationBloc.mapClickedGoogleLoginToState (package:blabla/blocs/authentication/AuthenticationBloc.dart:77:42)
I/flutter (29757): <asynchronous suspension
```

**Comment by adityadroid** [comment]
> Hi, I have created my own package and followed all your steps. On application start after pressing Sign in with google I get a dialog box with account selection However when I select my gmail , application, there will be a quick flicker on
> the screen then application shows me the start page where it asks me to "Sign In with google". I get following error:
> 
> ```
> W/ActivityThread(29757): handleWindowVisibility: no activity for token android.os.BinderProxy@81c22e0
> I/flutter (29757): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:569:7)
> I/flutter (29757): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:316:33)
> I/flutter (29757): <asynchronous suspension>
> I/flutter (29757): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:344:48)
> I/flutter (29757): <asynchronous suspension>
> I/flutter (29757): #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:218:23)
> I/flutter (29757): <asynchronous suspension>
> I/flutter (29757): #4      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:257:20)
> I/flutter (29757): #5      GoogleSignIn.signIn (package:google_sign_in/google_sign_in.dart:324:48)
> I/flutter (29757): #6      AuthenticationProvider.signInWithGoogle (package:blabla/providers/AuthenticationProvider.dart:18:28)
> I/flutter (29757): <asynchronous suspension>
> I/flutter (29757): #7      AuthenticationRepository.signInWithGoogle (package:blabla/repositories/AuthenticationRepository.dart:11:30)
> I/flutter (29757): #8      AuthenticationBloc.mapClickedGoogleLoginToState (package:blabla/blocs/authentication/AuthenticationBloc.dart:77:42)
> I/flutter (29757): <asynchronous suspension
> ```

Can you post your code?
Or link to the project repo, preferably.

**Comment by nepal12** [comment]
> 
> Can you post your code?
> Or link to the project repo, preferably.

https://github.com/nepal12/blabla

**Comment by adityadroid** [comment]
> > Can you post your code?
> > Or link to the project repo, preferably.
> 
> https://github.com/nepal12/blabla

I checked your code. This seems to be an issue with the **google-services.json** file in your `andorid/app` directory. 
Try removing that file and downloading and adding it again. Make sure:

1. That the SHA1 you enter while generating google-services.json is correct.
2. The package name is correct.

Refer
[Firestore Token retrieval failed: INVALID_SENDER](https://stackoverflow.com/questions/50987032/firestore-token-retrieval-failed-invalid-sender)

**Comment by adityadroid** [comment]
@nepal12 is the issue solved?

**Comment by adityadroid** [comment]
I think I've clarified your doubts. Feel free to open this issue back if needed.

**Comment by lakshit1** [comment]
I am also not able to login to app but i had added both sha, enabled google login, enabled database and storage.

**Comment by lakshit1** [comment]
I will be able to post log tomorrow. So, please wait for some time.

**Comment by adityadroid** [comment]
> I will be able to post log tomorrow. So, please wait for some time.

okay.

**Comment by lakshit1** [comment]
When i build this app and install it then i am not able to login but when i install this app running it from vscode then i am able login. Is this an issue or anything else ?

**Comment by adityadroid** [comment]
> When i build this app and install it then i am not able to login but when i install this app running it from vscode then i am able to login. Is this an issue or anything else ?

Are you using the same build environment in both places? I think you have different android SDK setup for VSCode and AS. You should either use the same SDK on both the places and use the SHA1 from that SDK. (SHA1 is generated using the debug key, which is generally the part of the android SDK unless you explicitly set it).

What you can do is:
1. Use any one editor and use the SHA1 from that editor to generate `google-services.json.`
Or
2. Use a common android SDK in both the editors.

**Comment by lakshit1** [comment]
Sorry for this much disturbance. I want to know that how to add another user. I had logged in from two devices with different accounts.

**Comment by lakshit1** [comment]
> > When i build this app and install it then i am not able to login but when i install this app running it from vscode then i am able to login. Is this an issue or anything else ?
> 
> Are you using the same build environment in both places? I think you have different android SDK setup for VSCode and AS. You should either use the same SDK on both the places and use the SHA1 from that SDK. (SHA1 is generated using the debug key, which is generally the part of the android SDK unless you explicitly set it).
> 
> What you can do is:
> 
> 1. Use any one editor and use the SHA1 from that editor to generate `google-services.json.`
>    Or
> 2. Use a common android SDK in both the editors.

Ok

**Comment by lakshit1** [comment]
I had already tried to add user by username option but not able to add user.

**Comment by adityadroid** [comment]
What issue are you facing while adding users? Can you explain/post logs?

**Comment by lakshit1** [comment]
![Screenshot (52)](https://user-images.githubusercontent.com/51991640/66381333-bde9cc80-e9d6-11e9-8de9-82d0b6f80ead.png)

This is the screen shot of error while adding user

**Comment by lakshit1** [comment]
![Screenshot (51)](https://user-images.githubusercontent.com/51991640/66381411-e40f6c80-e9d6-11e9-96e7-f82d821966ac.png)

This the screenshot while logging in to application.

**Comment by lakshit1** [comment]
These rules are defined in database.

![Screenshot (53)](https://user-images.githubusercontent.com/51991640/66382406-c6430700-e9d8-11e9-83ff-509f9868460f.png)

**Comment by adityadroid** [comment]
In the last two lines remove the condition which checks for uid matching.
I'll write a separate post on firebase rules towards the end of this series.

**Comment by lakshit1** [comment]
![Screenshot (54)](https://user-images.githubusercontent.com/51991640/66387105-e4ad0080-e9e0-11e9-88dc-9a298c4ae642.png)

like this ?

**Comment by adityadroid** [comment]
Yes. This will work.

**Comment by adityadroid** [comment]
Closing the issue for now. Feel free to open it back if the issue persists.
